name: Gerar Instalador e Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Ativar Compilador da Microsoft
        uses: ilammy/msvc-dev-cmd@v1

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Instalar Nuitka
        run: pip install nuitka

      - name: Compilar Cliente com Nuitka
        run: python -m nuitka --assume-yes-for-downloads --standalone --windows-console-mode=disable --lto=yes --output-dir=dist main.pyw

      - name: Compilar Atualizador com Nuitka
        run: python -m nuitka --assume-yes-for-downloads --standalone --windows-console-mode=disable --lto=yes --jobs=2 --output-dir=dist atualizador.pyw

      - name: Executar rotina manual de organizacao de arquivos
        shell: powershell
        run: |
          $acc_path = python -c "import accessible_output2, os; print(os.path.dirname(accessible_output2.__file__))"
          Copy-Item -Path $acc_path -Destination dist\main.dist\accessible_output2 -Recurse
          Copy-Item -Path "C:\Windows\System32\vcruntime140.dll" -Destination dist\main.dist\
          Copy-Item -Path "C:\Windows\System32\msvcp140.dll" -Destination dist\main.dist\
          Copy-Item -Path dist\atualizador.dist\* -Destination dist\main.dist -Recurse -Force
          Rename-Item -Path dist\main.dist\main.exe -NewName clientmud.exe
          Copy-Item -Path version -Destination dist\main.dist\version
          Rename-Item -Path dist\main.dist -NewName clientmud
          New-Item -ItemType Directory -Force -Path Output

      - name: Zipar pasta compilada
        run: Compress-Archive -Path dist\clientmud -DestinationPath Output\ClientMUD_Portable.zip

      - name: Compilar Instalador
        run: iscc instalador.iss

      - name: Criar Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Output/Instalador_ClientMUD.exe
            Output/ClientMUD_Portable.zip
          generate_release_notes: true
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}